# Generated by Django 3.2.18 on 2023-04-12 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='users_images/default_avatar.jpg', upload_to='users_images'),
        ),
    ]
