# Generated by Django 3.2.18 on 2023-03-06 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230306_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailverification',
            old_name='user_id',
            new_name='user',
        ),
    ]
